from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import os, time, requests, html5lib
from bs4 import BeautifulSoup

# Generating target url
top_url = "https://www.instagram.com/"
account_name = "starbucks_j"
target_url = top_url + account_name + "/"

# instance of Chrome headless browser by selenium
options = webdriver.ChromeOptions()
options.add_argument('--headless')
driver = webdriver.Chrome(options=options)
# driver = webdriver.Chrome()

driver.get(target_url)

html = driver.page_source

l = []

while True:

    # Scrolling browser down to the bottom
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # Waiting 2sec for loading additional images generated by ProfilePageContainer.js
    time.sleep(2)

    # judging it reaches at the bottom of the page
    html_check = driver.page_source
    if html != html_check:
        html = html_check

        # Getting target html by Beautiful Soup
        # the new element added by each scroll and also old elements disapperared so that have to get html everytime the elements loaded
        bs = BeautifulSoup(html, 'html5lib')
        url_list = bs.select('img.FFVAD')
        for target in url_list:
            url = target.attrs['srcset'].split(',')
            if url not in l:
                l.append(url)
    else:
        break

# lists of urls for each size of images
l_150 = []
l_240 = []
l_320 = []
l_480 = []
l_640 = []


# Getting urls for each image
for url in l:
    url_150 = url[0].replace(" 150w", "")
    url_240 = url[1].replace(" 240w", "")
    url_320 = url[2].replace(" 320w", "")
    url_480 = url[3].replace(" 480w", "")
    url_640 = url[4].replace(" 640w", "")

    l_150.append(url_150)
    l_240.append(url_240)
    l_320.append(url_320)
    l_480.append(url_480)
    l_640.append(url_640)


# Output the list of image urls to "target.txt"
with open("target.txt", mode="w") as f:
    f.write('size: 150w\n')
    for a in l_150:
        f.write(str(a) + '\n')
    f.write('size: 240w\n')
    for b in l_240:
        f.write(str(b) + '\n')
    f.write('size: 320w\n')
    for c in l_320:
        f.write(str(c) + '\n')
    f.write('size: 480w\n')
    for d in l_480:
        f.write(str(d) + '\n')
    f.write('size: 640w\n')
    for e in l_640:
        f.write(str(e) + '\n')

driver.close()
